# Generated by Django 5.2 on 2025-05-18 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_recipes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='shopping_cart',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscriptions',
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'constraints': [models.UniqueConstraint(fields=('user', 'subscribe'), name='unique_user_subscribe'), models.CheckConstraint(condition=models.Q(('user', models.F('subscribe')), _negated=True), name='prevent_self_subscription')],
            },
        ),
    ]
